import { Strings } from "@generated/Strings";

/**
 * Copy of the `forest` screen, grouped by the `Strings` namespace it comes from.
 *
 * The template never spells a string: it reads a field of this module, and every
 * field is a generated constant. That keeps the screen's copy in one reviewable
 * list and makes a key that stops existing a type error rather than a blank page.
 */
export const ForestCopy = {
  Forest: {
    yuyeonghun: Strings.Forest.yuyeonghun,
    _202609: Strings.Forest._202609,
    saundeuMiksingJipjungMyeongsangAepIos: Strings.Forest.saundeuMiksingJipjungMyeongsangAepIos,
    padoBiBaramMoraeJangjakDaseot2: Strings.Forest.padoBiBaramMoraeJangjakDaseot2,
    wonhaneunBiyulroSeokeoNamanuiSorireulMandeuneun: Strings.Forest.wonhaneunBiyulroSeokeoNamanuiSorireulMandeuneun,
    jamdeulTtaenaJipjunghalTtaeBaegyeongeumeuroTeuleoduneun: Strings.Forest.jamdeulTtaenaJipjunghalTtaeBaegyeongeumeuroTeuleoduneun,
    reulHwalyonghaeSayongjaInteobyuDijainPeurototaipeul: Strings.Forest.reulHwalyonghaeSayongjaInteobyuDijainPeurototaipeul,
    onboding: Strings.Forest.onboding,
    hom: Strings.Forest.hom,
    saundeu: Strings.Forest.saundeu,
    girok: Strings.Forest.girok,
    gineung: Strings.Forest.gineung,
    saundeuMiksing: Strings.Forest.saundeuMiksing,
    reieo5GaereulGakgakBolryumJojeolhae: Strings.Forest.reieo5GaereulGakgakBolryumJojeolhae,
    pado: Strings.Forest.pado,
    bi: Strings.Forest.bi,
    baram: Strings.Forest.baram,
    morae: Strings.Forest.morae,
    jangjak: Strings.Forest.jangjak,
    peurisetNamanuiMikseu: Strings.Forest.peurisetNamanuiMikseu,
    jeonyeokMulgyeolSupsokAchimDeungPeuriset: Strings.Forest.jeonyeokMulgyeolSupsokAchimDeungPeuriset,
    sumyeonTaimeo: Strings.Forest.sumyeonTaimeo,
    _15304560BunDwi: Strings.Forest._15304560BunDwi,
    girokTonggye: Strings.Forest.girokTonggye,
    sNsLoginNaeJeongboDonggihwa: Strings.Forest.sNsLoginNaeJeongboDonggihwa,
    chugaYejeong: Strings.Forest.chugaYejeong,
    gudokMitInaepGyeoljeIap: Strings.Forest.gudokMitInaepGyeoljeIap,
    seukil: Strings.Forest.seukil,
    swiftSwiftUi: Strings.Forest.swiftSwiftUi,
    kotlinCompose: Strings.Forest.kotlinCompose,
    typeScript: Strings.Forest.typeScript,
    hono: Strings.Forest.hono,
    cloudflareWorkers: Strings.Forest.cloudflareWorkers,
    d1: Strings.Forest.d1,
    r2: Strings.Forest.r2,
    openApi: Strings.Forest.openApi,
    baekendeuWaeIreotgeGolratna: Strings.Forest.baekendeuWaeIreotgeGolratna,
    hosting: Strings.Forest.hosting,
    cloudflareWorkersHono: Strings.Forest.cloudflareWorkersHono,
    seobeoreulJikjeopGuchukUnyeonghaneunDaesinKodeuman: Strings.Forest.seobeoreulJikjeopGuchukUnyeonghaneunDaesinKodeuman,
    db: Strings.Forest.db,
    d1SqLite: Strings.Forest.d1SqLite,
    workersAneseoBaroSseulSuItneun: Strings.Forest.workersAneseoBaroSseulSuItneun,
    storage: Strings.Forest.storage,
    r2EumwonJeojangso: Strings.Forest.r2EumwonJeojangso,
    pailNaeryeobateulTtaeButneunJeonsongEgress: Strings.Forest.pailNaeryeobateulTtaeButneunJeonsongEgress,
    auth: Strings.Forest.auth,
    jacheJwtInjeungIkmyeongRogeuin: Strings.Forest.jacheJwtInjeungIkmyeongRogeuin,
    hoewongaipJeolchaEoliGigimaneuroBaroSseul: Strings.Forest.hoewongaipJeolchaEoliGigimaneuroBaroSseul,
    iOsAndroidNaranhi: Strings.Forest.iOsAndroidNaranhi,
    gateunHandoffPaekijieseoDuPeulraetpomiDongsie: Strings.Forest.gateunHandoffPaekijieseoDuPeulraetpomiDongsie,
    iOsSwiftUi: Strings.Forest.iOsSwiftUi,
    hwamyeon4GaeOnbodingHomSaundeu: Strings.Forest.hwamyeon4GaeOnbodingHomSaundeu,
    aVAudioEngineGiban5TeuraekDongsiMiksing2: Strings.Forest.aVAudioEngineGiban5TeuraekDongsiMiksing2,
    aPiTongsinDeiteoModelOpeurainMokeop: Strings.Forest.aPiTongsinDeiteoModelOpeurainMokeop,
    saeksangTaipoGangyeokDeungDijainTokeun: Strings.Forest.saeksangTaipoGangyeokDeungDijainTokeun,
    androidJetpackCompose: Strings.Forest.androidJetpackCompose,
    iOsWaDongilhanHwamyeonKeomponeonteuGuseongeul: Strings.Forest.iOsWaDongilhanHwamyeonKeomponeonteuGuseongeul,
    odioMikseuPeulreieoGuhyeon: Strings.Forest.odioMikseuPeulreieoGuhyeon,
    aPiKeulraieonteuOpeurainMokeopPolbaekGyecheung: Strings.Forest.aPiKeulraieonteuOpeurainMokeopPolbaekGyecheung,
    aepSangtaeByumodelgwaDanwiTeseuteu4: Strings.Forest.aepSangtaeByumodelgwaDanwiTeseuteu4,
    iAepeulMandeunDogu: Strings.Forest.iAepeulMandeunDogu,
    handoffAgentSePeulraetpomeulHanBeone: Strings.Forest.handoffAgentSePeulraetpomeulHanBeone,
    handoffAgentSangse: Strings.Forest.handoffAgentSangse,
    gaeyo: Strings.Forest.gaeyo,
    gineungSeukil: Strings.Forest.gineungSeukil,
    baekendeu: Strings.Forest.baekendeu,
    iOsAndroid: Strings.Forest.iOsAndroid,
  },
  Resume: {
    handoffAgent: Strings.Resume.handoffAgent,
    forest: Strings.Resume.forest,
  },
} as const;
