import { Strings } from "@generated/Strings";

/**
 * Copy of the `resume` screen, grouped by the `Strings` namespace it comes from.
 *
 * The template never spells a string: it reads a field of this module, and every
 * field is a generated constant. That keeps the screen's copy in one reviewable
 * list and makes a key that stops existing a type error rather than a blank page.
 */
export const ResumeCopy = {
  Resume: {
    yuyeonghun: Strings.Resume.yuyeonghun,
    _01Sogae: Strings.Resume._01Sogae,
    _02MandeunGeot: Strings.Resume._02MandeunGeot,
    _03Gyeongryeok: Strings.Resume._03Gyeongryeok,
    softwareEngineerIosBuilder: Strings.Resume.softwareEngineerIosBuilder,
    iOsNeitibeuAepGaebaleulJuroMatawatjiman: Strings.Resume.iOsNeitibeuAepGaebaleulJuroMatawatjiman,
    ilhadaBanbokdoeneunMunjereulMannamyeon: Strings.Resume.ilhadaBanbokdoeneunMunjereulMannamyeon,
    dogureulJikjeopMandeuleoHaegyeol: Strings.Resume.dogureulJikjeopMandeuleoHaegyeol,
    hagoGeuDoguroDasiSeobiseureulMandeuneun: Strings.Resume.hagoGeuDoguroDasiSeobiseureulMandeuneun,
    choegeuneneunIosAndroidReulTtaroGaebalhamyeo: Strings.Resume.choegeuneneunIosAndroidReulTtaroGaebalhamyeo,
    handoffAgent: Strings.Resume.handoffAgent,
    raneunPeulreogeuineuroPuleotgo: Strings.Resume.raneunPeulreogeuineuroPuleotgo,
    jigeumeunGeuDoguro: Strings.Resume.jigeumeunGeuDoguro,
    forest: Strings.Resume.forest,
    raneunSeobiseureulMandeulgoItseupnida: Strings.Resume.raneunSeobiseureulMandeulgoItseupnida,
    wonchik1: Strings.Resume.wonchik1,
    gwichaneumeunAidieouiSijakjeom: Strings.Resume.gwichaneumeunAidieouiSijakjeom,
    banbokdoeneunEopmugaGwichandagoNeukkyeojilTtaeJeoneun: Strings.Resume.banbokdoeneunEopmugaGwichandagoNeukkyeojilTtaeJeoneun,
    wonchik2: Strings.Resume.wonchik2,
    geungeoroMalhapnida: Strings.Resume.geungeoroMalhapnida,
    gitHub: Strings.Resume.gitHub,
    yeonghunYooGmailCom: Strings.Resume.yeonghunYooGmailCom,
    gyeongryeok: Strings.Resume.gyeongryeok,
    skill: Strings.Resume.skill,
    _02MandeunGeot2: Strings.Resume._02MandeunGeot2,
    dogureulMandeulgoGeuDoguroSeobiseureulMandeupnida: Strings.Resume.dogureulMandeulgoGeuDoguroSeobiseureulMandeupnida,
    claudeCodePeulreogeuin202609: Strings.Resume.claudeCodePeulreogeuin202609,
    saundeuMiksingJipjungMyeongsangAep2026: Strings.Resume.saundeuMiksingJipjungMyeongsangAep2026,
    teuripeideuTripaidIosNative: Strings.Resume.teuripeideuTripaidIosNative,
    _202510Hyeonjae: Strings.Resume._202510Hyeonjae,
    helmidakAiChaetingGeongangsangdamSeobiseu: Strings.Resume.helmidakAiChaetingGeongangsangdamSeobiseu,
    appStore: Strings.Resume.appStore,
    iOsNeitibeuAepGaebalMitAkitekcheo: Strings.Resume.iOsNeitibeuAepGaebalMitAkitekcheo,
    iOsuiuxJeongbiMitPeulraetpom: Strings.Resume.iOsuiuxJeongbiMitPeulraetpom,
    neteuwokeuGongtongInteosepteoDoipMitTokeun: Strings.Resume.neteuwokeuGongtongInteosepteoDoipMitTokeun,
    claudeDesignEulHwalyonghanDijainSoyo: Strings.Resume.claudeDesignEulHwalyonghanDijainSoyo,
    holricheuHolich: Strings.Resume.holricheuHolich,
    _2023042025021Nyeon: Strings.Resume._2023042025021Nyeon,
    letSBeePilripinEumsikBaedal: Strings.Resume.letSBeePilripinEumsikBaedal,
    _202407202501Flutter: Strings.Resume._202407202501Flutter,
    guLetSBeeKeulrakJiyeok: Strings.Resume.guLetSBeeKeulrakJiyeok,
    _202306202411Ios: Strings.Resume._202306202411Ios,
    myConectHotelBidaemyeonSeobiseuPeulraetpom: Strings.Resume.myConectHotelBidaemyeonSeobiseuPeulraetpom,
    _202304202412Ios: Strings.Resume._202304202412Ios,
    juAlpaigeulru: Strings.Resume.juAlpaigeulru,
    _2020112022031Nyeon: Strings.Resume._2020112022031Nyeon,
    sajugibanAiIreumJakmyeongSeobiseuNeitibeu: Strings.Resume.sajugibanAiIreumJakmyeongSeobiseuNeitibeu,
    gyeoljePeuroseseuIsyuHaegyeol: Strings.Resume.gyeoljePeuroseseuIsyuHaegyeol,
    githubComYeonghunyoo: Strings.Resume.githubComYeonghunyoo,
  },
  Handoff: {
    claudeDesignHaendeuopeuPaekiji1Gaero: Strings.Handoff.claudeDesignHaendeuopeuPaekiji1Gaero,
    sangseBogi: Strings.Handoff.sangseBogi,
    pIpeline: Strings.Handoff.pIpeline,
    dijainHaendeuopeu1GaeIosAndroid: Strings.Handoff.dijainHaendeuopeu1GaeIosAndroid,
    input: Strings.Handoff.input,
    claudeDesignSanchulmul: Strings.Handoff.claudeDesignSanchulmul,
    refine: Strings.Handoff.refine,
    reiautTeuriJson: Strings.Handoff.reiautTeuriJson,
    interview: Strings.Handoff.interview,
    seupekMunseoSeontaekjiPyo: Strings.Handoff.seupekMunseoSeontaekjiPyo,
    iOs: Strings.Handoff.iOs,
    android: Strings.Handoff.android,
    backend: Strings.Handoff.backend,
    verify: Strings.Handoff.verify,
    peuronteuBaekendeuInpeuraInteobyuGyeolgwareulTodaero: Strings.Handoff.peuronteuBaekendeuInpeuraInteobyuGyeolgwareulTodaero,
    iOsAndroidBackendDongsiSaengseong: Strings.Handoff.iOsAndroidBackendDongsiSaengseong,
    inteobyuGibanBaekendeuInpeuraGyeoljeonggujoMit: Strings.Handoff.inteobyuGibanBaekendeuInpeuraGyeoljeonggujoMit,
    mingamJeongboInjeungseoKiNeunSayongjaga: Strings.Handoff.mingamJeongboInjeungseoKiNeunSayongjaga,
  },
  Forest: {
    padoBiBaramMoraeJangjakDaseot: Strings.Forest.padoBiBaramMoraeJangjakDaseot,
    handoffAgentReulHwalyonghanIosAndroid: Strings.Forest.handoffAgentReulHwalyonghanIosAndroid,
    swiftUiJetpackComposeGateunHwamyeonKeomponeonteu: Strings.Forest.swiftUiJetpackComposeGateunHwamyeonKeomponeonteu,
    cloudflareWorkersHonoD1R2Baekendeu: Strings.Forest.cloudflareWorkersHonoD1R2Baekendeu,
    seobeoGwanriBudamEoliIGyumoeseo: Strings.Forest.seobeoGwanriBudamEoliIGyumoeseo,
    aVAudioEngineGiban5TeuraekDongsiMiksing: Strings.Forest.aVAudioEngineGiban5TeuraekDongsiMiksing,
    reieobyeolBolryumPeurisetSumyeonTaimeo: Strings.Forest.reieobyeolBolryumPeurisetSumyeonTaimeo,
  },
} as const;
